apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: albarbaro-tesing
  title: AlBarbaro Testing
  description: Artist Lookup
  tags:
    - java
    - data
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
  annotations:
    github.com/project-slug: albarbaro-org/some-test
    backstage.io/techdocs-ref: url:https://github.com/albarbaro-org/some-test
    lighthouse.com/website-url: https://backstage.io
    backstage.io/linguist: 'https://github.com/backstage/backstage/tree/master/plugins/playlist'
    quay.io/repository-slug: abarbaro/busybox
spec:
  type: library
  owner: Myself
  lifecycle: experimental
