apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: some-test-service # Give your component a meaningful name
  description: A test service for TechDocs integration.
  annotations:
    # This tells TechDocs to look for mkdocs.yml and docs/
    # in the root of THIS repository.
    backstage.io/techdocs-ref: dir .
spec:
  type: service
  lifecycle: experimental # Or production, development, etc.
  owner: guests # Replace with the actual owner/team in your RHDH instance
  system: some-system # Optional, but good practice
