site_name: backstage-showcase
site_description: 'User documentation for Janus Showcase'
repo_url: https://github.com/janus-idp/backstage-showcase
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - Onboard: index.md
  - Test:
      - Migration Process Overview: test/test.md
